Repository green-touch/caring-demo-app, pull requests merged in 2025-01, with the labels that each got.

#6 [SWEP-12] PR 템플릿 및 이슈 템플릿 설정
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/버그-해결.md
  .github/ISSUE_TEMPLATE/사용자-정의.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📎 CHORE, :memo: DOCS

#8 [CARE-12] 이슈 컨벤션 및 PR 컨벤션 정리
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📎 CHORE, :memo: DOCS

#13 [CARE-11] 리드미 파일 초기 설정
  README.md
Labels: :memo: DOCS

#12 [CARE-10] 네트워크 연결 타입과 상태 체크하는 함수 구현
  .yarnrc.yml
  App.tsx
  android/app/build.gradle
  android/app/src/main/java/com/greeuntouch_demo_app/BatteryModule.kt
  android/app/src/main/java/com/greeuntouch_demo_app/BatteryPackage.kt
  android/app/src/main/java/com/greeuntouch_demo_app/MainApplication.kt
  android/app/src/main/java/com/greeuntouch_demo_app/ScreenReceiverModule.kt
  android/app/src/main/java/com/greeuntouch_demo_app/ScreenReceiverPackage.kt
  android/gradlew
  package.json
  src/hooks/useBatteryLevel.ts
  src/hooks/useScreenStatus.ts
  yarn.lock
Labels: :sparkles: FEAT

#16 chore: 기능 페이지 / UI 페이지 분해
  App.tsx
  declaration.d.ts
  index.ts
  package.json
  src/assets/icons/SampleHome/ic_map_pin.svg
  src/assets/icons/index.ts
  src/components/SvgIcon.tsx
  src/features/featureA/index.ts
  src/features/featureB/index.ts
  src/features/shared/README.md
  src/screens/HomeScreen.tsx
  src/screens/MainScreen.tsx
  src/screens/SampleHomeScreen.tsx
  src/screens/TestScreen.tsx
  tailwind.config.js
  yarn.lock
Labels: 📎 CHORE

#17 [CARE-23] 기능 페이지 / UI 페이지 분해
  App.tsx
  declaration.d.ts
  index.ts
  metro.config.js
  package.json
  src/assets/icons/SampleHome/ic_map_pin.svg
  src/assets/icons/index.ts
  src/components/SvgIcon.tsx
  src/features/featureA/index.ts
  src/features/featureB/index.ts
  src/features/shared/README.md
  src/screens/HomeScreen.tsx
  src/screens/MainScreen.tsx
  src/screens/SampleHomeScreen.tsx
  src/screens/TestScreen.tsx
  tailwind.config.js
  yarn.lock
Labels: 📎 CHORE

#21 UI: 홈 UI (+ Header & BottmBar)
  package.json
  src/assets/icons/ic_account_24.svg
  src/assets/icons/ic_account_active_32.svg
  src/assets/icons/ic_account_disabled_32.svg
  src/assets/icons/ic_alert_circle_24.svg
  src/assets/icons/ic_alert_default_24.svg
  src/assets/icons/ic_alert_triangle_24.svg
  src/assets/icons/ic_back_32.svg
  src/assets/icons/ic_battery_alert_32.svg
  src/assets/icons/ic_battery_black_24.svg
  src/assets/icons/ic_battery_off_black_24.svg
  src/assets/icons/ic_battery_off_red_24.svg
  src/assets/icons/ic_battery_off_yellow_24.svg
  src/assets/icons/ic_battery_red_24.svg
  src/assets/icons/ic_battery_yellow_24.svg
  src/assets/icons/ic_bell_32.svg
  src/assets/icons/ic_check_round_blue_32.svg
  src/assets/icons/ic_checkbox_checked_24.svg
  src/assets/icons/ic_checkbox_default_24.svg
  src/assets/icons/ic_chevron_down_24.svg
  src/assets/icons/ic_chevron_right_18.svg
  src/assets/icons/ic_chevron_right_24.svg
  src/assets/icons/ic_chevron_right_32.svg
  src/assets/icons/ic_close_32.svg
  src/assets/icons/ic_current_location_24.svg
  src/assets/icons/ic_eye_remove_24.svg
  src/assets/icons/ic_eye_visible_24.svg
  src/assets/icons/ic_globe_off_24.svg
  src/assets/icons/ic_globe_on_24.svg
  src/assets/icons/ic_home_active_32.svg
  src/assets/icons/ic_home_disabled_32.svg
  src/assets/icons/ic_lock_24.svg
  src/assets/icons/ic_map_filled_24.svg
  src/assets/icons/ic_map_line_18.svg
  src/assets/icons/ic_map_pin_filled_18.svg
  src/assets/icons/ic_phone_filled_24.svg
  src/assets/icons/ic_phone_filled_black_24.svg
  src/assets/icons/ic_remove_round_24.svg
  src/assets/icons/ic_search_32.svg
  src/assets/icons/ic_wifi_24.svg
  src/assets/icons/ic_wifi_off_alert_32.svg
  src/assets/icons/index.ts
  src/assets/images/img_center_detail.png
  src/assets/images/img_center_empty.png
  src/assets/images/img_center_list.png
  src/assets/images/img_user.png
  src/assets/images/imt_user_empty.png
  src/components/main/Header.tsx
  src/components/main/StatusBox.tsx
  src/screens/MainScreen.tsx
  src/screens/MyInfoScreen.tsx
  src/screens/SampleHomeScreen.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: :sparkles: FEAT

#23 fix: 단순 에러 해결
  App.tsx
  src/assets/icons/SampleHome/ic_map_pin.svg
  src/components/main/StatusBox.tsx
  src/screens/SampleHomeScreen.tsx
Labels: :bug: FIX

#25 fix+refactor: 각종 컴포넌트화 및 UI 에러 해결
  src/assets/images/img_user_empty.png
  src/components/PlatformSpecificButton.tsx
  src/components/SvgIcon.tsx
  src/components/main/CallButton.tsx
  src/components/main/StatusBox.tsx
  src/components/main/StatusBoxComponents/BatteryAlert.tsx
  src/components/main/StatusBoxComponents/BatteryStatus.tsx
  src/components/main/StatusBoxComponents/NetworkStatus.tsx
  src/components/main/StatusBoxComponents/StatusIndicator.tsx
  src/components/main/WelfareNew.tsx
  src/screens/MainScreen.tsx
  src/screens/MyInfoScreen.tsx
  src/screens/SampleHomeScreen.tsx
  src/types/bottomBar.ts
  src/types/homeScreen.ts
  src/types/icon.ts
  src/types/statusBox.ts
Labels: :bug: FIX, :recycle: REFACTOR

#26 refactor: WhiteBox 모듈화
  src/layout/WhiteBox.tsx
  src/screens/SampleHomeScreen.tsx
Labels: :recycle: REFACTOR

#27 feat, fix: 절대경로 설정
  App.tsx
  babel.config.js
  metro.config.js
  package.json
  src/components/PlatformSpecificButton.tsx
  src/components/SvgIcon.tsx
  src/components/main/CallButton.tsx
  src/components/main/Header.tsx
  src/components/main/StatusBox.tsx
  src/components/main/WelfareNew.tsx
  src/components/myInfo/FamilyInfoBox.tsx
  src/components/myInfo/MyInfoWhiteBox.tsx
  src/layouts/WhiteBox.tsx
  src/screens/HomeScreen.tsx
  src/screens/MainScreen.tsx
  src/screens/MyInfoScreen.tsx
  src/screens/SampleHomeScreen.tsx
  src/screens/TestScreen.tsx
  src/types/familyInfo.ts
  src/types/icon.ts
  src/types/statusBox.ts
  tsconfig.json
  yarn.lock
Labels: :bug: FIX, :sparkles: FEAT

#28 [CARE-25] 내정보 UI 구현 및 절대경로 설정
  App.tsx
  babel.config.js
  metro.config.js
  package.json
  src/components/PlatformSpecificButton.tsx
  src/components/SvgIcon.tsx
  src/components/main/CallButton.tsx
  src/components/main/Header.tsx
  src/components/main/StatusBox.tsx
  src/components/main/WelfareNew.tsx
  src/components/myInfo/FamilyInfoBox.tsx
  src/components/myInfo/MyInfoWhiteBox.tsx
  src/layouts/WhiteBox.tsx
  src/screens/HomeScreen.tsx
  src/screens/MainScreen.tsx
  src/screens/MyInfoScreen.tsx
  src/screens/SampleHomeScreen.tsx
  src/screens/TestScreen.tsx
  src/types/familyInfo.ts
  src/types/icon.ts
  src/types/statusBox.ts
  tsconfig.json
  yarn.lock
Labels: :bug: FIX, 📎 CHORE, :sparkles: FEAT
